<a href="https://colab.research.google.com/github/SamuelLlaiqui/Pyhton-Learning/blob/master/Pyhton_Learn_Tips_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
a.size
a.ndim
a.shape

(5,)

# OPERACIONES

In [ ]:
b = np.array([1,2,3,4,5])
a + b
a- b

array([0, 0, 0, 0, 0])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a = np.array([1,2,3,4,5], dtype = float)
a

array([1., 2., 3., 4., 5.])

In [ ]:
a = np.array([1,2,3,4,5], dtype = bool)
a

array([ True,  True,  True,  True,  True])

In [ ]:
a = np.array([1,2,3,4,5], dtype = complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [ ]:
a = np.array([1,2,3,4,5], dtype = str)
a

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,5, dtype = float)

array([1., 2., 3., 4.])

In [ ]:
np.zeros(10, dtype = str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [ ]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.random.randint(0,100,88)

array([29, 30, 90, 12, 16, 47, 19, 33, 74, 11, 28, 22, 14, 86, 44, 31, 60,
       14, 77, 64, 22, 56, 60, 87, 44, 70, 40, 39, 56, 65, 79, 92, 27, 58,
       15, 22, 77, 79, 91, 68, 50, 31, 53, 38, 96, 90, 68, 67, 43, 43, 80,
       70,  2, 16, 73, 97, 47,  6, 44, 87, 77, 56, 55,  6, 39, 59, 65, 39,
       52, 79, 21, 67, 15, 18, 29, 18, 19, 46, 18, 95, 36, 62, 28, 78, 76,
        9, 66, 82])

In [ ]:
a = np.random.randint(0,10,10)
a

array([9, 7, 5, 3, 2, 5, 7, 3, 2, 6])

In [ ]:
a[0:5]

array([9, 7, 5, 3, 2])

# SUBARREGLOS

In [ ]:
a = np.random.randint(0,10,4)
a

array([3, 8, 8, 5])

In [ ]:
a[0::3]
# Recordar que a[Start:End:Salto]

array([1, 5, 1, 0, 0, 1, 4, 2, 8, 1])

In [ ]:
a[[0,1,2]]  #Para buscar varios elmentos en un array

array([1, 1, 4])

In [ ]:
a[[True,True,False,True]]  #Tambien se puede calcular o hallar los numeros con codigos booleanos, y estos tiene que tener la misma cantidad

array([3, 8, 5])

# VECTORIZAR FUNCIONES

In [ ]:
a = np.random.randint(0,10,20)
a

array([1, 8, 9, 1, 8, 4, 0, 6, 5, 0, 9, 9, 0, 5, 7, 6, 2, 1, 3, 6])

In [ ]:
def operacion(valor):
  return (valor ** 2) + 2

In [ ]:
operacion(a)

array([ 3, 66, 83,  3, 66, 18,  2, 38, 27,  2, 83, 83,  2, 27, 51, 38,  6,
        3, 11, 38])

In [ ]:
vector = np.vectorize(operacion)
np.vectorize?

In [ ]:
vector(a)

array([ 3, 66, 83,  3, 66, 18,  2, 38, 27,  2, 83, 83,  2, 27, 51, 38,  6,
        3, 11, 38])

In [ ]:
operacion(a)

array([ 3, 66, 83,  3, 66, 18,  2, 38, 27,  2, 83, 83,  2, 27, 51, 38,  6,
        3, 11, 38])

# COPIAS Y VISTAS
Copias = Nuevo arreglo el cual fue creado a partir de otro, posse los mismos objetos


Vistas = Una vista al arreglo original


In [ ]:
b = np.arange(0,10) #Arreglo original
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b.copy()  #Copia

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = b.copy()
print(id(a.base))
print(id(b))    #Ambos Id's son diferentes, por lo que es una copia

101388607132640
138367347517616


In [ ]:
a[1] = 12
a

array([ 0, 12,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a.view()  #view

array([ 0, 12,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
c = a.view()
print(id(c.base))
print(id(a))  #Ambos Id's son iguales, por lo que es una vista

138367345663920
138367345663920


In [ ]:
# Otra forma de hacer una view
d = a[:]
a is d.base

True

# ARREGLOS MULTIDIMENSIONALES

In [ ]:
a = np.array([[1,2,3,4,5],
              [3,5,3,1,2],
              [6,4,12,3,4],
              ])
a

array([[ 1,  2,  3,  4,  5],
       [ 3,  5,  3,  1,  2],
       [ 6,  4, 12,  3,  4]])

In [ ]:
print(a.ndim)
print(a.shape)   #Axis 0 = Fila  Axis 1 = Columna
print(a.size)

2
(3, 5)
15


In [ ]:
a[0][2]

3

In [ ]:
a[0,[0,4]]

array([1, 5])

In [ ]:
a[:,3]

array([4, 1, 3])

In [ ]:
a[[0,2],3]

array([4, 3])

# METODOS DE AGREGACIÓN

In [ ]:
a

array([[ 1,  2,  3,  4,  5],
       [ 3,  5,  3,  1,  2],
       [ 6,  4, 12,  3,  4]])

In [ ]:
a.std()    #Desviacion Éstandas

2.578543947441829

In [ ]:
a.sum()     #Suma de todos los arregos del modelo

58

In [ ]:
a.min()     #Calcula el valor minimo
a.max()       #Calcula el maximo

12

In [ ]:
a.mean()      #Promedio

3.8666666666666667

In [ ]:
a[1].sum()

14

In [ ]:
a[2].max()

12

In [ ]:
a[:,2].mean()

6.0

In [ ]:
# prompt: calculame el promedio para cada columna

import numpy as np

a = np.array([[1,2,3,4,5],
              [3,5,3,1,2],
              [6,4,12,3,4],
              ])

# Calculate the mean of each column
column_means = np.mean(a, axis=0)

column_means

array([3.33333333, 3.66666667, 6.        , 2.66666667, 3.66666667])

In [ ]:
# prompt: calculmae le promedio para la segunda fila

import numpy as np

a = np.array([[1,2,3,4,5],
              [3,5,3,1,2],
              [6,4,12,3,4],
              ])

# Calculate the mean of the second row (index 1)
second_row_mean = np.mean(a[:,2])

second_row_mean

6.0

# TRASPOSICION

In [ ]:
a

array([[ 1,  2,  3,  4,  5],
       [ 3,  5,  3,  1,  2],
       [ 6,  4, 12,  3,  4]])

In [ ]:
a.T

array([[ 1,  3,  6],
       [ 2,  5,  4],
       [ 3,  3, 12],
       [ 4,  1,  3],
       [ 5,  2,  4]])

In [ ]:
a.size
a.shape

(3, 5)

#  FILTROS Y CONDICIONES

In [ ]:
a = np.random.randint(0,100,50)
a

array([12, 63, 71, 37, 14, 11, 92, 38, 46, 90, 30, 82, 95, 32, 55,  1, 78,
       42, 82, 86, 85, 15, 22, 10,  7, 32, 64, 93, 76,  0, 54,  9, 69, 21,
       85, 77, 94, 26, 71, 21, 69, 17, 80, 85, 37, 51, 27, 96,  3, 28])

In [ ]:
b = np.array(a > 50, dtype = int)
b

array([0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0])

In [ ]:
a<50

array([ True, False, False,  True,  True,  True, False,  True,  True,
       False,  True, False, False,  True, False,  True, False,  True,
       False, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False,  True, False, False,
       False,  True, False,  True, False,  True, False, False,  True,
       False,  True, False,  True,  True])

In [ ]:
a[a<50]

array([12, 37, 14, 11, 38, 46, 30, 32,  1, 42, 15, 22, 10,  7, 32,  0,  9,
       21, 26, 21, 17, 37, 27,  3, 28])

In [ ]:
a[(a>50) & (a<90)]  #Siempre debe estar entre parentesis en caso haya 2 logicas

array([63, 71, 82, 55, 78, 82, 86, 85, 64, 76, 54, 69, 85, 77, 71, 69, 80,
       85, 51])

In [ ]:
a[(a==10)|(a==49)|(a<5)]

array([ 1, 10,  0,  3])

In [ ]:
np.all(a>50)    #Ejecuta que todos los elementos cumplan con la condicion, basta que uno no cumpla no, dara false

False

In [ ]:
np.all(a>=0)

True

In [ ]:
# prompt: calcula en caso, por lo menos 1 datos de la matriz a, es menor a 10

import numpy as np

a = np.array([[1,2,3,4,5],
              [3,5,3,1,2],
              [6,4,12,3,4],
              ])

# Check if at least one element in array 'a' is less than 10
if np.any(a < 10):
  print("At least one element in 'a' is less than 10")
else:
  print("No element in 'a' is less than 10")